introduced chat features
Saadadeel8/React-Firebase-Chat-Application pull request #2
Opened 2021-09-02 11:45 UTC by Saadadeel8

2021-09-02 12:01 UTC, Saadadeel8 commented on src/App.css
> +}
Extra Line

2021-09-02 12:02 UTC, Saadadeel8 commented on src/App.js
> +  console.log(user)
Remove console

2021-09-03 06:01 UTC, sheheryar-pirzada commented on src/Components/ChatPreview.js
> +        else{console.log('Select Receiver')}
no need for else condition unless you are showing this message to the user

2021-09-03 06:02 UTC, sheheryar-pirzada commented on src/Components/ChatPreview.js
> +            db.collection("messages").doc([user.displayName, receiver].sort().join("-"))
store `[user.displayName, receiver].sort().join("-")` in a `const` or create a function for it as it is being used in multiple places

2021-09-03 06:02 UTC, sheheryar-pirzada commented on src/Components/ChatPreview.js
> +                var messages = [];
use `let` instead

2021-09-03 06:03 UTC, sheheryar-pirzada commented on src/Components/ChatPreview.js
> +    }, [receiver.length])
i guess, just `receiver` is fine

2021-09-03 06:03 UTC, sheheryar-pirzada commented on src/Components/ChatPreview.js
> +            var users = [];
`let`

2021-09-03 06:06 UTC, sheheryar-pirzada commented on src/Components/ChatPreview.js
> +            userData.Contacts.forEach((contact) => {friends.push(contact)});
would something like :
`let friends = userData.Contacts.map((contact) => contact);` work?

2021-09-03 06:08 UTC, sheheryar-pirzada commented on src/Components/ChatPreview.js
> +                displayName})
brackets on next line, and remove extra line

2021-09-03 06:08 UTC, sheheryar-pirzada commented on src/Components/ChatPreview.js
> +                    <a href=" " title="Sign Out" style={{color: 'white'}}><button onClick={handleLogout}><LogoutOutlined /></button></a>
indent

2021-09-03 06:09 UTC, sheheryar-pirzada commented on src/Components/ChatPreview.js
> +                    <a href=" " title="Sign Out" style={{color: 'white'}}><button onClick={handleLogout}><LogoutOutlined /></button></a>
fix href

2021-09-03 06:10 UTC, sheheryar-pirzada commented on src/Components/ChatPreview.js
> +                    {friendList.filter(user => user.Name.toLowerCase().includes(search)).map((object, index) => (
change `object` to something more meaningful, like 'friend'

2021-09-03 06:11 UTC, sheheryar-pirzada commented on src/Components/ChatPreview.js
> +                    : null}
indentation

2021-09-03 06:12 UTC, sheheryar-pirzada commented on src/Components/ChatPreview.js
> +                    <div className='text-area'><TextArea value={text} onChange={(e) => setText(e.target.value)} placeholder="Enter Message" /></div>
in className you're using single quotes, and in placeholder you use double quotes.
Keep it consistent. Better to use single quotes :)
fix this throughout the app

2021-09-03 06:12 UTC, sheheryar-pirzada commented on src/Components/Helpers/Routes.js
>  import ChatPreview from '../../Components/ChatPreview'
semi colons :)

2021-09-03 06:12 UTC, sheheryar-pirzada commented on src/Components/Helpers/Routes.js
> +function Routes({user}) {
instead of `function`,  create a big arrow function, in all your components

2021-09-03 06:13 UTC, sheheryar-pirzada commented on src/Components/Helpers/Routes.js
> +                  {user?.uid ?
indent

2021-09-03 06:13 UTC, sheheryar-pirzada commented on src/Components/Login.js
> +import {auth} from './Services/base';
space before and after `auth`

2021-09-03 06:13 UTC, sheheryar-pirzada commented on src/Components/Login.js
>            name="normal_login"
avoid snake_case

2021-09-03 06:15 UTC, sheheryar-pirzada requested changes
Comments are applicable on entire app, don't just resolve comments on the line i commented on. 
Otherwise good work :)

2021-09-03 09:46 UTC, merged